### PR TITLE
feat: adding header and footer

### PR DESCRIPTION
**Pull request by theJohnnyMe**
Adding basic routing + header & footer + two pages to test basic routing and Tegel components.

Added a base url to allow for refresh and deep linking.

### CODE REVIEW

**Comment by theJohnnyMe** [comment]
> Nice! I tried going directly to the second page, or refreshing the page when I an on the second page and then I get a 404?

I think it should be fixed now, got some improvements in routing.

**Comment by theJohnnyMe** [comment]
Actually @mJarsater I think issue is still present in Netlify, but not on my local... maybe it is something due to link and routing issues. Worth looking more into just not sure will have time now for it...

**Comment by mJarsater** [comment]
> Actually @mJarsater I think issue is still present in Netlify, but not on my local... maybe it is something due to link and routing issues. Worth looking more into just not sure will have time now for it...

I can have a look really quickly and then we can move on.

**Review by mJarsater — APPROVED** [review]
🥫

**Pull request merged**
